### ISSUE TITLE
Support for compressed snapshots

### ISSUE THREAD

**Issue by davide125** [npwoods/bletchmame#128]
MAME can read snapshots if they're compressed, e.g. by setting `snapshot_directory` to `/foo/snap` it'll read stuff `/foo/snap.zip` if that exists. It'd be nice to support the same in BletchMAME too, the same way we support reading icons from a zipfile.

**Comment by npwoods** [comment]
I agree; one of the problems I ran into (if I recall correctly) was that Qt doesn't provide a good way to have a file dialog that lets users select either files or directories.

If a technique for doing that could be identified, things would be quite easy.

**Comment by belegdol** [comment]
qmc2 has a button switching between folder and file for snaps, titles, etc.

**Comment by npwoods** [comment]
Also, I should take note that for now, only ZIP is supported, not 7z.  QuaZip doesn't seem to support 7-Zip.  I'll make this more explicit in the readme.

**Comment by belegdol** [comment]
Please feel free to ignore if this is a known limitation: at least on linux, the only way of getting this working right now is to edit the config xml by hand. The selection dialog does not allow to select a file as per https://github.com/npwoods/bletchmame/issues/128#issuecomment-882108996.

**Comment by npwoods** [comment]
You should be able to edit the paths, MAMEUI style, by clicking on the paths in the paths dialog, bypassing Qt's file dialog.  Does this not work on Linux?

**Comment by belegdol** [comment]
I did not know that, it does work indeed.
