### ISSUE TITLE
Not working with mame-0.235 and 0.234 (error parsing attribute "refresh")

### ISSUE THREAD

**Issue by belegdol** [npwoods/bletchmame#143]
With at least 0.235 and 0.234, building MAME info database fails with a spew of listxml parsing errors, producing a popup way to tall to fit on screen (I am not going to attach it here in order not to break github). The error is:
```
Error parsing XML from MAME -listxml: 211:2: Error parsing attribute “refresh” (text="60.000000")
458:2: Error parsing attribute "refresh" (text="60.000000")
....
```
The list of emulated systems stays empty.

**Comment by belegdol** [comment]
I have narrowed it down to an issue with decimal separator. Both of my machines are set to locales which use comma and not a period. If I run BletchMAME with `LANG=C`, machine info can be built.

**Comment by belegdol** [comment]
Apparently https://en.cppreference.com/w/cpp/utility/from_chars could help but I do not know how to do that myself.

**Comment by belegdol** [comment]
This compiles and runs, but I have no idea how correct it is:
```patch
diff --git a/src/xmlparser.cpp b/src/xmlparser.cpp
index 820893b..f211123 100644
--- a/src/xmlparser.cpp
+++ b/src/xmlparser.cpp
@@ -8,6 +8,7 @@
 
 #include <expat.h>
 #include <inttypes.h>
+#include <charconv>
 #include <string>
 
 #include <QBuffer>
@@ -87,10 +88,9 @@ namespace
        public:
                bool operator()(const std::string &text, T &value) const
                {
-                       char *endptr;
-                       float f = strtof(text.c_str(), &endptr);
-                       if (endptr != text.c_str() + text.size())
-                               return false;
+                       float f;^M
+                       const auto format = std::chars_format::general;
+                       const auto res = std::from_chars(text.data(), text.data() + text.size(), f, format);
 
                        value = (T)f;
                        return value == f;
```

**Comment by npwoods** [comment]
Thanks for the pointer - do you want to be credited as "belegdol" or your real name?

**Comment by belegdol** [comment]
I would prefer my real name. Thanks!

**Comment by npwoods** [comment]
Ugh, any idea my builds are failing #145?  I tried doing something like this on Godbolt and it worked fine

**Comment by belegdol** [comment]
Please note that I know next to nothing about C++ so this might be nonsense.

It appears that it is necessary to declare the data type of the fourth parameter to be std::chars_format as it currently gets interpreted as integer. I used const auto format = std::chars_format::general and then used format in the function. I think we can even use std::chars_format::fixed as the refresh rate is unlikely to be provided in scientific notation.

**Comment by belegdol** [comment]
Well I can actually build your branch with gcc-11.2.1. So maybe it is just bad C++17 support in whatever the CI is using?

**Comment by npwoods** [comment]
You're right; I get the problem on godbolt.org with gcc 10.3 but not gcc 11.1

**Comment by npwoods** [comment]
I got around the problem by using Qt's methods (I'll update to GCC 11 later).  Considering this one fixed!
