### ISSUE TITLE
Does this front support IPS?

### ISSUE THREAD

**Issue by jlu511** [npwoods/bletchmame#149]
Does this front support IPS? I hope that. Thanks

**Comment by npwoods** [comment]
Well ummmm... what is IPS?

**Comment by npwoods** [comment]
If you're talking about the patching format, BletchMAME cannot support it without core MAME supporting it.

**Comment by jlu511** [comment]
yes, ips is a  function of patching roms for playing some hack games.  It can save a lot of HD spaces.

**Comment by jlu511** [comment]
long long ago, a frontend named mameplus can support it, but it was never update.

**Comment by npwoods** [comment]
Yeah, MAMEPlus was more than a frontend - it was a derivative of MAME that not only had a front end on it, but it also added a bunch of random bells and whistles to core MAME.

BletchMAME being a pure front end and not a MAME derivative, is reliant on MAME itself providing functionality like this.
