### ISSUE TITLE
Input seems to stop after toggling options and settings menu and F11

### ISSUE THREAD

**Issue by randomuser4444** [npwoods/bletchmame#295]
**Input seems to stop after toggling options and settings menu. **UPDATE**: _I just noticed F11 does this too._

- Run any game, keyboard input works fine, _example_, inserting credit or moving around the emulated menu.
- Simply click on Bletch's Menu options example; toggle **Options** and **Settings** menu. Just simply bring up the pulldown menus don't need to select anything.
- Game no no longer accepts inputs.
- You can try and re click the game window or menus etc filldle around but inputs don't work until a hard restart or close/open Bletch.

**Comment by npwoods** [comment]
I think I may have a fix for this.  I don't want to unilaterally declare victory yet... try it out!

**Comment by randomuser4444** [comment]
It's I just tested with 2.12.0.20 and it's improved, but still happens when you toggle fullscreen or run aroiund the menus, but if you show the about dialoge and close it seems to fix inputs again.

**Comment by randomuser4444** [comment]
Cool, I just got the latest version and spammed the emulater and the UI and it didn't loose imputs. Closing now.

**Comment by randomuser4444** [comment]
Just one thing, if you bring up the **debugger** it seems to loose input then, not sure if this is a quick fix or a pain, but thought I would let you know.

**Comment by davide125** [comment]
I can repro a variant of this issue on Linux with 2.13. When starting any game, input isn't working. If I toggle full screen with F11, then input starts working normally.
