### ISSUE TITLE
Black screen when opening ROMs

### ISSUE THREAD

**Issue by james-martin-engineer** [npwoods/bletchmame#401]
Hi all,

When I attempt to run a game using the MAME 0.256, I see a normal loading screen for a few milliseconds, then a dialog with black contents.

I've tried this with a simpler game like Double Dragon and a more complex game like Ultimate Mortal Kombat. Both have the same outcome. Both ROMs are tested using IVPlay with MAME 0.256

Eventually I get an error saying "timeout waiting for status update from MAME"

What am I doing wrong here?

Heres a [screen capture](https://www.dropbox.com/scl/fi/ye1upduycvfv89oiw1ngv/bletchmame.png?rlkey=yyx9lcr2qzxyllov494i8gncd&dl=0)

**Comment by npwoods** [comment]
I think there is a legit issue here.

For some reason the version of MAME that I build myself doesn't have this problem, but before I discounted this report I wanted to make sure that I didn't see the problem with the off the shelf binaries from www.mamedev.org, and I reproduced the problem.

I'll look into this - and thanks for the report!

**Comment by npwoods** [comment]
I was able to trace this to something that happens to be present when I build MAME myself, but is not on the MAME 0.256 release binaries
https://mametesters.org/view.php?id=8712

**Comment by npwoods** [comment]
Fixed with the BletchMAME 2.17 release
